### ISSUE TITLE
Fix this known issue in ChatModule in android 

### ISSUE THREAD

**Issue by tushardubey121** [QuickBlox/quickblox-flutter-sdk#1]
The event shrink is not updating when receiving the message update the code

`@Override
    public void onListen(Object arguments, EventChannel.EventSink eventSink) {
        if (arguments != null) {
            this.eventName = arguments.toString();
        }
        this.eventSink = eventSink;
        updateListeners();
    }
`

`  private void updateListeners() {
        for (EventHandler eventHandler : eventHandlers) {
            if (eventHandler.eventName.equals(eventName)) {
                eventHandler.eventSink = this.eventSink;
                break;
            }
        }
    }`

at line number 59 in `class EventHandler`

**Comment by kirillTolmachev** [comment]
Hello.
Please try to use the last version of SDK 0.3.9-alpha
