### ISSUE TITLE
Event subscriptions duplicates and subscription cancel not working

### ISSUE THREAD

**Issue by sergiyloza** [QuickBlox/quickblox-flutter-sdk#10]
Hi,

In event subscription functions like below. listen function create a `StreamSubscription` which should be canceled in future 

`Future<void> subscribeMessageEvents(String eventName, eventMethod) async {
    EventChannel(eventName)
        .receiveBroadcastStream(eventName)
        .listen(eventMethod);
  }`

but unsubscribe function look like which is wrong and subscriptions are not removed after function call.

`Future<void> unsubscribeMessageEvents(String eventName) async {
    EventChannel(eventName).receiveBroadcastStream(eventName).listen(null);
  }`

The subscriptions should be returned from first function and can be canceled by consumer when needed.

Also event callback work in different manner on iOS and Android.

iOS always receive own events back in callback. When sending a message from iOS client this client also receive new message event, but Android receive events only from other users.

**Comment by sergiyloza** [comment]
Small example subscriptions bug https://github.com/sergiyloza/QBBugsDemo

**Comment by anky21** [comment]
Hi @sergiyloza. seems you have made some progress with this sdk. I was wondering whether you can give me a hand. 
In my app, users can have 1 on 1 chats. I was just wondering how I can send a push to the other user when I send a message. 

I'm using this manual push (refer [here](https://docs.quickblox.com/docs/flutter-push-notifications#create-push-subscription)) to achieve this:
      var qbEvent = await QB.events.create(
          QBNotificationEventTypes.ONE_SHOT,
          QBNotificationTypes.PUSH,
          qbUser.id,
          {"title": "Portugal vs. Denmark", "body": "great match!"},
          recipientsIds: ['121528928']);

However, I got this error:
PlatformException(No one can receive the message, null, null)

Could you please shed some light on how to notify the other user whenever there is a new chat message? 
I would like to thank you in advance.

**Comment by sergiyloza** [comment]
Hi, @anky21 make sure there that another user has notifications subscription in QB admin panel. 
Subscription should be created like described below, get device toke and create a subscription. Then other user should be joined to chat.

`if (Platform.isAndroid) {
          _userSubscription =
              await QB.subscriptions.create(token, QBPushChannelNames.GCM);
        } else if (Platform.isIOS) {
          _userSubscription =
              await QB.subscriptions.create(token, QBPushChannelNames.APNS);
        }`

And iOS certificates and firebase key also should be added on QB admin panel

**Comment by RaashVision** [comment]
Bro have you used 3.3.0-alpha.  In android I does not received any message in subscription event page . There is log that I received the message , but I just didn't received anything in subscription event function. Do you encountered the same thing?

**Comment by kirillTolmachev** [comment]
Hello.
Please try to use the last version of SDK 0.3.9-alpha.
