### ISSUE TITLE
Does not received any message in subscription function in 3.3.0-aplha

### ISSUE THREAD

**Issue by RaashVision** [QuickBlox/quickblox-flutter-sdk#12]
Does anyone able to received any message in subscription event function on lib 3.3.0-apha. I received the log that message received but I just received them in subscription event function. Have anyone experience the same thing?

**Comment by Vov4yk** [comment]
I have similar. Get messages after first connection. But lost stream after reconnect. 
Same in 0.3.4-alpha as well

**Comment by kirillTolmachev** [comment]
Hello.
Please try to use the latest SDK version 0.3.9-alpha

**Comment by Vov4yk** [comment]
Hello,
think is that I’m already using the latest 0.3.9-alpha

**Comment by kirillTolmachev** [comment]
@Vov4yk 
Does the issue still reproduce?

**Comment by Vov4yk** [comment]
Yes.
Still can’t upload .pdf / .mp4 files on android.

**Comment by kirillTolmachev** [comment]
> Yes. Still can’t upload .pdf / .mp4 files on android.

Please write the name of the library and version which you use for uploading files.

**Comment by Vov4yk** [comment]
I’m sorry, Kirill.

But I’m not sure that I did understood you well. Do you have an access to the original ticket I posted on support board?

So, I’m using
QB Flutter SDK 0.3.9-alpha to upload a file by given path where it’s locating. Please, see attachments in this mail. There are bloc of code I'm using and some addition info.


The line that throw the exception is
final QBFile file = await QB.content.upload(url, public: true);

And as I mention in original ticket. That code works good for iOS platform and from uploading an image on android. Only troubles I faced that can’t upload video and pdf on Android platform.

Please advice.

**Comment by kirillTolmachev** [comment]
Yes. Our support team has created a ticket for this issue. 
Can you provide the link to a library that you use to get files from the file system?
I mean something like that: https://pub.dev/packages/file_picker

**Comment by Vov4yk** [comment]
Sure,
I’m using

file_picker: ^2.1.1 for PDF
https://pub.dev/packages/file_picker


and
image_picker: ^0.6.7+14 for Video
https://pub.dev/packages/image_picker

**Comment by kirillTolmachev** [comment]
Thanks. 
I understood that doesn't work file_picker with PDF and other files (any files) but image_picker with video and photo files works correctly.
Is it correct?

**Comment by Vov4yk** [comment]
@kirillTolmachev Sorry for confusion. It's because mess in my mailbox. I've mixed up few issues. 
that one work well, thank you. It can be closed.

**Comment by kirillTolmachev** [comment]
Please update the Flutter Quickblox SDK to the last version 0.3.10-alpha.
The last version has a fix for uploading files in Android.
