### ISSUE TITLE
During call terminate App

### ISSUE THREAD

**Issue by umairAsifVeemed** [QuickBlox/quickblox-flutter-sdk#13]
Hi

during call, when I force quit the App, call is still live, other person can see me but in my Android phone, I quit the App forcefully.

Kindly help me, how to handle it?

**Comment by kirillTolmachev** [comment]
Hello.
The Android handles the video calls in service and you can continue calling after killing the application. 
We made this feature for the sharing screen which we will add in the future.
For correct end call, you should handle the lifecycle of the application and when the application goes to the background you should hang-up call.
