### ISSUE TITLE
proper documentation for Video implementation and Video stream not working

### ISSUE THREAD

**Issue by davidAg9** [QuickBlox/quickblox-flutter-sdk#15]
I looked everywhere in the documentation on how to properly implement the video call stream cos I thought I follow it wrong but couldn't find anything ,everything form calling to end call to incoming etc works ; all except when the call is answered and there is no stream coming through just the container  widgets showing  black

**Comment by kirillTolmachev** [comment]
Hello.
Please try to use the example in [pub.dev Quickblox flutter SDK](https://pub.dev/packages/quickblox_sdk/example)
Do not forget to add permissions for the camera, and file system like the image below:

![permissions](https://user-images.githubusercontent.com/41300382/104585872-5c022300-566d-11eb-8f27-e4ee8fa14b7b.jpg)

**Comment by stephanoparaskeva** [comment]
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by davidAg9** [comment]
Great finally 
,I have been looking for a solution to my problem ...I will join the community now
