### ISSUE TITLE
Unable to get video call when the app is killed.. 

### ISSUE THREAD

**Issue by RashidaBegamShaik** [QuickBlox/quickblox-flutter-sdk#16]
1. When the app is in foreground/background video calling is working fine... but when the app is killed , not able to get video call.
How to get a video call when the app is killed in flutter...

**Comment by devmaster19** [comment]
Hey Rashida, are you able to find the solution for this? I am facing the same issue in flutter

**Comment by kirillTolmachev** [comment]
You can use **push notifications** to start the application, get a session, and show a video call.
When the application is killed there is not possible to get anything information from the chat. WebRTC Signaling uses chat messages.

**Comment by devmaster19** [comment]
> You can use **push notifications** to start the application, get a session, and show a video call.
> When the application is killed there is not possible to get anything information from the chat. WebRTC Signaling uses chat messages.

Thanks Kirill, I will implement and update here

**Comment by Do-Varun1306** [comment]
Hello Kirill,  I am facing similar issue, even I tried push notification as well. If my flutter application is open or in background then I have no problem  receiving video calls using push notification.  Problem comes when user Killed application or Logout and Login again, that time Quickblox is not able to find old session or not able to create new session for that particular user for video call.  Your foreground services is running continually, but after login again / killed apps no session found. Please help

**Comment by Do-Varun1306** [comment]
@kirill-dobrynin

**Comment by kirillTolmachev** [comment]
@Do-Varun1306 
Hello.
Important notice. 
After ending the call you should invoke the method **release Video Views**

Please provide more detailed steps to reproduce the issue.

**Comment by Do-Varun1306** [comment]
@kirillTolmachev Hi Kirill, Yes I am doing so, I know that. 
In JavaScript App:
Step 1.  We useQB.init() and QB.createSession() initialize the App Session.
Step 2.  After that we login the QB user. If it does not exist, a new is created. Also connected to Chat using QB.chat.connect().
Step 3.  Used QB.webrtc.createNewSession to get a new session for video call. Using the created session get access to camera and mic for video calling (session.getUserMedia).
Step 4.  Once the camera and mic access is granted. We call the opponent using session.call().

Now on Flutter App:
Step 1. Using QB.settings.init() initialized app session
Step 2. Get login and password of user from our API
Step 3. Login to QuickBlox // Create User and login
Step 4. QB.chat.connect()
Step 5. subscribeRTCEvent(QBRTCEventTypes.CALL, (callData){})
Step 6. set up call end and hang up listeners
Step 7. Received FCM notification with call session Id. Accept reject using this session Id => QB.webrtc.accept() or QB.webrtc.reject()
After Step 7 : `QBRTCEventTypes.HANG_UP` callback is not triggered.

Also, in some cases I get connection to Chat Error : `PlatformException(No response received within reply timeout. Timeout was 5000ms (~5s). Used filter: No filter used or filter was 'null'., null, null, null)`

**Comment by kirillTolmachev** [comment]
@Do-Varun1306 
I don't understand the logic of your application but you can check your flow like below:

1. When the application in the foreground state you can get the calls from the Android service (webRTC.init) with subscriptions of course.

2. When the application in the background state you can get calls from FCM, afterward you should start the Android service (webRTC.init) and get the session with subscriptions of course.

Resume: push notifications need only to wake-up device and start the application.

Please check the issue in our examples https://github.com/QuickBlox/quickblox-flutter-sdk/tree/master/examples

If your issue won't resolve please write to the support team and we can check your code and found the appropriate solution.
Thanks.

**Comment by stephanoparaskeva** [comment]
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by shaikhTaha97** [comment]
QB subscriptions for getting call session is getting called too late i get call after 3-5 seconds after i tap on the notification and app initialization. 
Is there any workaround?
