### ISSUE TITLE
Flutter run error on android

### ISSUE THREAD

**Issue by mtkgeek** [QuickBlox/quickblox-flutter-sdk#17]
I'm trying to add quickblox to my flutter app. I already followed every installation step but when i try to run the app i keep getting this error
`A problem occurred configuring project ':quickblox_sdk'.
> Could not load compiled classes for build file 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\quickblox_sdk-0.3.3-alpha\android\build.gradle' from cache. Expected class file C:\Users\'me\.gradle\caches\jars-8\97d1c2d42c9f1541565069daf605930b\proj.jar\build_7qd4hzik9g0x0eofma4i94k5s.class does not exist.
> Could not get unknown property 'android' for project ':quickblox_sdk' of type org.gradle.api.Project.`

**Comment by kirillTolmachev** [comment]
Please try to clean your pub-cache.

**Comment by stephanoparaskeva** [comment]
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g
