### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.quickblox.chat.QBSystemMessagesManager.removeSystemMessageListener(com.quickblox.chat.listeners.QBSystemMessageListener)' on a null object reference

### ISSUE THREAD

**Issue by deepbhavsar** [QuickBlox/quickblox-flutter-sdk#20]
The app is crashing when disconnecting the chat. 
I have also tried to subscribe RECEIVED_SYSTEM_MESSAGE message and RECEIVED_NEW_MESSAGE. Also, I cancel both on dispose method. 
Stucked with it.

**Comment by kirillTolmachev** [comment]
Please update the Quickblox Flutter SDK to version **0.4.2-beta**

**Comment by deepbhavsar** [comment]
Yes @kirillTolmachev , it works on Flutter SDK to version 0.4.2-beta. Thank you
