### ISSUE TITLE
Login after logout in same device but senderId has not changed.

### ISSUE THREAD

**Issue by deepbhavsar** [QuickBlox/quickblox-flutter-sdk#21]
I have two accounts. I am log out from one account and log in using another account on the same device. It is not updating the sender Id when I am sending the messages.  It is sending messages using the previously logged-in user Id.

I have tried disconnect the user before logout but it crashes the android app.

I am also stuck with it. please suggest some way.

**Comment by stephanoparaskeva** [comment]
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g

**Comment by kirillTolmachev** [comment]
@deepbhavsar 
Please clarify, what do you mean about **sender id**

**Comment by deepbhavsar** [comment]
@kirillTolmachev , It also works fine on Flutter SDK to version 0.4.2-beta. still, let me explain it. I log in using **a@demo** after I log out and again login into the same device with **b@demo**. It gives me a proper dialog list but when I send a message then it is sending using **a@demo** instead of **b@demo**. 
It is like old users stay there even after log out.

**Comment by tarun18s** [comment]
@deepbhavsar  i got same issue when i m using SDK 0.6. bcoz i cannot use 0.4.2-beta bcoz of null shefty can u help me what i can do

**Comment by ghost** [comment]
@tarun18s Hello,

This is Nikolay from QuickBlox support.

To investigate the issue, we need the following points:
1. Please specify the platform (Android, iOS, or both).
2. Version of the platform (e.g. Android 11, iOS 13).
3. Devices in use (e.g. Redmi 8, iPhone 12).
4. Please specify the exact SDK version you use.
5. Please provide us with full REST + XMPP logs as an attachment in .txt format. There should be logs from application start and User 1 login till sending a message from User 2.
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/article/368-how-can-i-enable-quickblox-logs)
6. Flutter version.
7. Dart version.

@deepbhavsar Please let us know if you found a solution.
