### ISSUE TITLE
Crash while initializing quickBLOX

### ISSUE THREAD

**Issue by pranjaljain011** [QuickBlox/quickblox-flutter-sdk#24]
After creating Release APK In flutter, App is Crashing while Loading ChatRooms? but working fine debug mode and debug APK. tried all the methods didn't work any leads ?

**Comment by kirillTolmachev** [comment]
Hello @pranjaljain011 
Can you provide a logs and proguard file for Android?

**Comment by pranjaljain011** [comment]
org.jivesoftware.smack.SmackConfiguration.getVersion (SmackConfiguration.java)
org.jivesoftware.smack.ConnectionConfiguration.<clinit> (ConnectionConfiguration.java)
com.quickblox.chat.QBChatService.<clinit> (QBChatService.java)
com.quickblox.chat.QBChatService.access$200 (QBChatService.java)
com.quickblox.quickblox_sdk.settings.SettingsModule.b (SettingsModule.java:207)
com.quickblox.quickblox_sdk.settings.SettingsModule.a (SettingsModule.java:115)
com.quickblox.quickblox_sdk.settings.-$$Lambda$YvhPoCECtZjQHXFykmfFvy4np_g.onMethodCall (-.java:2)
io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.a (MethodChannel.java:17)
io.flutter.embedding.engine.dart.DartMessenger.a (DartMessenger.java:57)
io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage (FlutterJNI.java:4)
android.os.MessageQueue.nativePollOnce (MessageQueue.java)
android.os.MessageQueue.next (MessageQueue.java:336)
android.os.Looper.loop (Looper.java:181)
android.app.ActivityThread.main (ActivityThread.java:7560)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)
![Screen Shot 2021-05-25 at 19 35 26](https://user-images.githubusercontent.com/61407381/119511945-863cbd80-bd90-11eb-9752-7fe6b4f02ebb.png)

**Comment by pranjaljain011** [comment]
I am not using Progaurd this is the firebase Crashlytics Output on crash.

**Comment by AnsarAzees** [comment]
buildTypes {
        release {
            minifyEnabled true
            proguardFile 'proguard-rules.pro'
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

update the build.gradle as above and copy proguard file to Android app folder 

[proguard-rules.pro.zip](https://github.com/QuickBlox/quickblox-flutter-sdk/files/6540169/proguard-rules.pro.zip)

**Comment by kirillTolmachev** [comment]
@AnsarAzees 
Thanks!

@pranjaljain011 
Please use the solution from @AnsarAzees or if you don't need the proguard and obfuscation please add the code like below:

buildTypes {
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            shrinkResources false
        }
    }

**Comment by kirillTolmachev** [comment]
-

**Comment by pranjaljain011** [comment]
@kirillTolmachev and @AnsarAzees  Thank you for your help. your answer solved my issues and I am ready to launch my application.

**Comment by sunil3590** [comment]
@pranjaljain011 what did you do to fix this? I have the same issue @suhasds

**Comment by pranjaljain011** [comment]
> @pranjaljain011 what did you do to fix this? I have the same issue @suhasds

buildTypes {
release {
signingConfig signingConfigs.debug
minifyEnabled false
shrinkResources false
}
}

Try this in your gradle file.
This helps me in solving my issue.
