### ISSUE TITLE
App Crash in iOS

### ISSUE THREAD

**Issue by kishorlogicrays** [QuickBlox/quickblox-flutter-sdk#29]
In the iOS app was a crash when I click on init credentials in the settings option.

Error:

Terminating app due to uncaught exception 'BaseServiceException', reason: 'Something wrong with your Api Endpoint. Please ensure that your apiEndpoint starts with https or http. f.e.: [QBSettings setApiEndpoint:@"https://your.production.apiendpoint" chatEndpoint:@"chatendpoint.com" forServiceZone:QBConnectionZoneTypeProduction];'
terminating with uncaught exception of type NSException

Please help to solve this issue

Thanks,

**Comment by ghost** [comment]
Hello,

This is Nikolay from QuickBlox support.

We can suggest double-checking the documentation regarding the authentication:
[https://docs.quickblox.com/docs/flutter-authentication](https://docs.quickblox.com/docs/flutter-authentication)

Please make sure that you don’t specify any custom endpoints in your code if you use our Cloud server and check whether your application credentials are correct.

If you do not have a QuickBlox account or applications, you can create a new one here: [https://admin.quickblox.com/signin](https://admin.quickblox.com/signin)
