### ISSUE TITLE
Complete sample

### ISSUE THREAD

**Issue by krongnang** [QuickBlox/quickblox-flutter-sdk#3]
Hi, Could you please share the simple complete source code
Thanks in advanced

----- Update ----
@kirillTolmachev has make a small sample over here!
https://github.com/QuickBlox/quickblox-flutter-sdk/issues/3#issuecomment-789711123

**Comment by mrcool17** [comment]
please share simple complete source code for chat and video call for flutter

**Comment by abdulsamad234** [comment]
Please, this isn't working wtf

**Comment by RaashVision** [comment]
Yes we need example code.

**Comment by anky21** [comment]
since you guys are working on the sdk, I wonder how hard it is for you to create a demo app🤔

**Comment by krongnang** [comment]
> since you guys are working on the sdk, I wonder how hard it is for you to create a demo app🤔

Yah, It's hard to implement

**Comment by anky21** [comment]
> > since you guys are working on the sdk, I wonder how hard it is for you to create a demo app🤔
> 
> Yah, It's hard to implement

Sorry. I meant to speak to the Quickblox devs. they have the ability to come up with an sdk. Shouldn't be too hard to provide a demo to us.

**Comment by kirillTolmachev** [comment]
Hello.
We are working on samples now.
You can see a small example from [flutter pub dev](https://pub.dev/packages/quickblox_sdk/example)

**Comment by osKlonowski** [comment]
Are there any updates on this issue? I am still unable to get the subscriptionToChatEvents working, a Flutter code sample would be very helpful.

**Comment by kirillTolmachev** [comment]
We have uploaded a small example with a simple UI where you can test Quickblox SDK 
[link](https://github.com/QuickBlox/quickblox-flutter-sdk/tree/master/examples)

**Comment by krongnang** [comment]
> We have uploaded a small example with a simple UI where you can test Quickblox SDK
> [link](https://github.com/QuickBlox/quickblox-flutter-sdk/tree/master/examples)

Thanks for your hard working.
