### ISSUE TITLE
Change setComplexProperty to setProperty !!

### ISSUE THREAD

**Issue by neon97** [QuickBlox/quickblox-flutter-sdk#30]
Sending custom objects as parameters in Messages for a Dialog in Quickblox with Flutter.

We aren't able to view that object in the dialog messages 
As, we went on debugging the same.

Checked that native **Android code** was working perfectly as expected.
On **Checking & Digging the SDK** we found that "setComplexProperty" as used in Flutter SDK.
And on Native their we have **setProperty** we tried using **setComplexProperty** there too but that didn't worked on Native.

So, we came with one .. is setComplexProperty is not adding the params to the custom data of the dialog messages so far. 

Where as, when we modified the SDK with **"setProperty"** we were able to send the Map as params to the dialog messages custom data.

Request to Quickblox to change the setComplexProperty to setProperty or else provide a functionality that we can achieve both of them with ease.

Earlier it was in this manner

`   if (properties != null && properties.size() > 0) {
            for (Map.Entry<String, Object> entry : properties.entrySet()) {
                String propertyName = entry.getKey();
                Object propertyValue = entry.getValue();
                qbChatMessage.setComplexProperty(propertyName, propertyValue);
            }
        }
`

We changed it to :

`        if (properties != null && properties.size() > 0) {
            for (Map.Entry<String, Object> entry : properties.entrySet()) {
                String propertyName = entry.getKey();
                Object propertyValue = entry.getValue();
                qbChatMessage.setProperty(propertyName, propertyValue.toString());
            }
        }`
        
This context has help to send custom data to the messages we needed in the dialog so as to use on APP for purpose.
Hope to be solved !!

**Comment by ghost** [comment]
Hello,

This is Nikolay from QuickBlox support.

Thank you for the detailed information. We will pass it to our development team.

Please make sure that you use the latest version of the QuickBlox Flutter SDK:
https://pub.dev/packages/quickblox_sdk/versions/0.5.2-beta

If you observe the same behavior on the latest version of the SDK, please let us know.

**Comment by ghost** [comment]
Hello Raj,

Thank you for your feedback.

We have just released a new version. Here is a link:
https://pub.dev/packages/quickblox_sdk/versions/0.6.0-beta

Now Android and iOS use the same properties with <String, String> parameters.

Please check it on your end and let me know if there are any questions.
