### ISSUE TITLE
How can be read images which sent through messages

### ISSUE THREAD

**Issue by pranjaljain011** [QuickBlox/quickblox-flutter-sdk#32]
How can we get read count of images sent. I am able to change read count after just text messages but not working for images. Is there any way to achieve this.

**Comment by ghost** [comment]
Hello Pranjal,

This is Nikolay from QuickBlox support.

We don’t have a feature of counting sent images by default. To achieve that functionality, you may try implementing custom logic on your end using custom objects, for example: 
[https://docs.quickblox.com/docs/flutter-custom-objects](https://docs.quickblox.com/docs/flutter-custom-objects)
