### ISSUE TITLE
How can we handle push notification callback to show chat screen?

### ISSUE THREAD

**Issue by AnsarAzees** [QuickBlox/quickblox-flutter-sdk#33]

**Comment by AnsarAzees** [comment]
Since we need to use Firebase for android and APNS for iOS, is there any way to handle it in flutter?

**Comment by ghost** [comment]
Hello Ansar,

This is Nikolay from QuickBlox support.

Such a callback is not provided for the QuickBlox Flutter SDK at the moment. You may try implementing it on your end.

On Flutter, you need to use both APNS and Firebase configurations. You can find more information here: [Push Notifications | Flutter SDK | QuickBlox](https://docs.quickblox.com/docs/flutter-push-notifications)

Processing of push notifications in the background mode and terminated state is up to the client-side.
