### ISSUE TITLE
Give an example boilerplate for call kit functionality using push notification

### ISSUE THREAD

**Issue by suhailzoft** [QuickBlox/quickblox-flutter-sdk#37]

**Comment by QB-nikolay-zolotarov** [comment]
Hello Suhail,

This is Nikolay from QuickBlox support.

Unfortunately, we don’t have complete Flutter samples at the moment.

A Flutter Video calling sample is being developed. We will release it as soon as it is finished and tested by our QA team. 

You will be able to check the implementation of functionality related to receiving calls and push notifications.
To our regret, there is no ETA as our Flutter developers are going to release a Flutter chat sample before releasing the Video calling sample.

**Comment by ghost** [comment]
Hello Suhail,

This is Nikolay from QuickBlox support.

Unfortunately, we don’t have complete Flutter samples at the moment.

A Flutter Video calling sample is being developed. We will release it as soon as it is finished and tested by our QA team.

You will be able to check the implementation of functionality related to receiving calls and push notifications.
To our regret, there is no ETA as our Flutter developers are going to release a Flutter chat sample before releasing the Video calling sample.

However, we have a code snippet that provides more understanding about handling push notifications in the background or killed state.

Please check the snippet if you are interested in it. I attached the .txt file.
[FlutterExample.txt](https://github.com/QuickBlox/quickblox-flutter-sdk/files/7209958/FlutterExample.txt)

Please note that it is an example and you need to write your own application logic on how push notifications received from the QuickBlox server will be processed on the client-side.
