### ISSUE TITLE
Subscribe to receive messages not working

### ISSUE THREAD

**Issue by hereshem** [QuickBlox/quickblox-flutter-sdk#4]
```
await QB.chat.subscribeMessageEvents(QBChatEvents.RECEIVED_NEW_MESSAGE, (data) {print("Message received $data")});
```
This does not show any print messages in logs.
But the following XMPP logs can be seen.
I have used flutter `quickblox_sdk: ^0.2.4-alpha`
I also tried with 0.2.3 and also with 0.2.2 had same issues.
```
D/SMACK   (13663): RECV (3): <message xmlns="jabber:client" id="5e9a7f32801c1a2ea519137c" from="106897563-81589@chat.quickblox.com/android_00000000-449d-7607-ffff-ffffef05ac4a" to="106898725-81589@chat.quickblox.com" type="chat"><paused xmlns="http://jabber.org/protocol/chatstates"/></message>
D/SMACK   (13663): RECV (3): <message xmlns="jabber:client" id="5e9a7f32801c1a2ea519137d" from="106897563-81589@chat.quickblox.com/android_00000000-449d-7607-ffff-ffffef05ac4a" to="106898725-81589@chat.quickblox.com" type="chat"><body>Test body message</body><markable xmlns="urn:xmpp:chat-markers:0"/><extraParams xmlns="jabber:client"><date_sent>1587183410</date_sent><save_to_history>1</save_to_history><dialog_id>5e9a7f21a28f9a690858b8b9</dialog_id><message_id>5e9a7f32801c1a2ea519137d</message_id></extraParams></message>
```

**Comment by chauhanumesh** [comment]
I am also getting the same issue. received message prints in the log but does not show any print messages in logs.

**Comment by RaashVision** [comment]
Same here I have no idea what I misss

**Comment by kirillTolmachev** [comment]
Hello.
Please try to use the last version of SDK 0.3.9-alpha.

**Comment by osKlonowski** [comment]
This issue is still present in version 0.3.10-alpha

**Comment by kirillTolmachev** [comment]
We have uploaded the examples dir with simple UI where you can test **subscribeMessageEvents** 
link: https://github.com/QuickBlox/quickblox-flutter-sdk/tree/master/examples

**Comment by hereshem** [comment]
Thanks @kirillTolmachev 
I will try them and let you know soon.

**Comment by stephanoparaskeva** [comment]
Hey please join a Community made QuickBlox Slack so we can help each other on the QB platform:

https://join.slack.com/t/quickbloxcommunity/shared_invite/zt-q0s3bx3b-YzacqhEfPeBGbEdgEtFr1g
