### ISSUE TITLE
The opponent video is not showing on both ends when calling to the iOS device.

### ISSUE THREAD

**Issue by suhail-zartek** [QuickBlox/quickblox-flutter-sdk#41]
The opponent video is not showing on both ends when calling to the iOS device. But, It’s working on the android device and web. Also, It was working before. Even the old builds which worked before are not working right now.

Additionally, The remote RTCVideoViewController object getting from the RTCVideoView is null. That is the root cause of the issue. So, when trying to call play function I’m getting errors because of it.

**Comment by vivekf16** [comment]
@QB-nikolay-zolotarov  
I also got this issue I have checked below test case for this.

Android to Android => Working fine
Android to iOS => Working fine
iOS to iOS => Only the opponent caller video is shown.
iOS to Android => Not able to accept or reject calls (All webrtc events not working).



Version : ^0.6.1-beta

**Comment by ghost** [comment]
@suhail-zartek @Anonymousthe1 
Hello,

This is Nikolay from QuickBlox support.

The issue is being investigated.

Once there is any news, I will let you know.

**Comment by ghost** [comment]
@suhail-zartek @Anonymousthe1
Please double-check the application workflow:

    open app (from background or icon)
    settings → init credentials
    auth → login
    chat → connect, subscribe to events
    webrtc → init, subscribe to events
    receive the call (or another) event
    app goes to background
    webrtc → unsubscribe, release
    chat → unsubscribe, disconnect

If you follow this order, the call (and another) event should be received correctly.

**Comment by QB-maksym-pidhorbunskyi** [comment]
Hello @suhail-zartek @Anonymousthe1 
We located the issue with local video only on iOS devices with iOS 15.x versions and after investigation and additional fixes, we released a new version of Flutter SDK 0.6.4-beta where the reported issue was fixed.
You can download the SDK here: https://pub.dev/packages/quickblox_sdk/versions

Additionally, please make sure that follow correct workflow:
- user accepts a call;
- start call screen;
- video view starts and controller has completed. Call back is called;
- received video track;
- start to render (call play method) a video track;
- a controller is complete and a user see the local video.
