### ISSUE TITLE
Sorting Descending not working

### ISSUE THREAD

**Issue by KAUSHIKTECHIE** [QuickBlox/quickblox-flutter-sdk#43]
Hi Guys,
    **QBSort sort = QBSort();
    sort.field = QBChatDialogSorts.LAST_MESSAGE_DATE_SENT;
    sort.ascending = false;
    int limit = 100;
    int skip = 0;**

_List<QBMessage?> messages = await QB.chat.getDialogMessages(dialogId,
          markAsRead: markAsRead, sort: sort, limit: limit!, skip: skip!);_

This method should ideally give me last 100 messages but I am not getting it.Instead I am getting first 100 for both    
**sort.ascending = false;  and sort.ascending = true;**

Can I know the reason why this happens ???.How can I get last N messages ??? Also want to load after the last N messages using the API.

**Comment by ishaforenkoqb** [comment]
Hi @KAUSHIKTECHIE , 

You're using incorrect field `QBChatDialogSorts.LAST_MESSAGE_DATE_SENT`, it's from Dialog model, not from Message. Use `QBChatMessageSorts.DATE_SENT` instead.

``` dart
QBSort sort = QBSort();
sort.field = QBChatMessageSorts.DATE_SENT;
sort.ascending = false;
```

**Comment by KAUSHIKTECHIE** [comment]
Thanks it works fine.
