### ISSUE TITLE
How to stop log reporting?

### ISSUE THREAD

**Issue by roldanunne** [QuickBlox/quickblox-flutter-sdk#48]
the webrtc is already release and chat also, but this continue to log.
![image](https://user-images.githubusercontent.com/4781184/149457144-74d60fab-e8a8-4595-a5c9-41eab9c4ab51.png)

**Comment by ghost** [comment]
@roldanunne Hello,

This is Nikolay from QuickBlox support.

Please make sure that WebRTC is released according to our documentation:
https://docs.quickblox.com/docs/flutter-video-calling#release-resource

Also, please make sure that the session is ended.
You may refer to the documentation:
https://docs.quickblox.com/docs/flutter-video-calling#end-a-call
