### ISSUE TITLE
Quickblox Flutter SDK example 

### ISSUE THREAD

**Issue by basilFodouly** [QuickBlox/quickblox-flutter-sdk#5]
Hi
great work,
Is there any example about video/audio call ,
I tried to implement the sdk in flutter but it not work in android and iOS , I think I did something wrong 
please , if there is any full example for using webrtc in video call, provide it to me
I want to use the sdk for big solution in big company in KSA

**Comment by efernandes-dev-ops** [comment]
Any updates on this? @kirillTolmachev

**Comment by efernandes-dev-ops** [comment]
Tbf I haven't had a chance to look at your documentation, I'm sure there's something on there. @basilFodouly this should just be your starting point and not full blown solution project that you can essentially plug and play

**Comment by yash1292002** [comment]
hi i have integrate quickBlox sdk for video call funcationality but it's not working in flutter
can you please help me if any one have sample code for video call
