### ISSUE TITLE
when we initialise web rtc it gives us error for android version 12 

### ISSUE THREAD

**Issue by vartikaantino** [QuickBlox/quickblox-flutter-sdk#51]
console log:

E/AndroidRuntime(30491): java.lang.RuntimeException: Unable to start service com.quickblox.quickblox_sdk.webrtc.WebRTCCallService@4d5c1f6 with Intent { cmp=com.antino.fitbasix.dev/com.quickblox.quickblox_sdk.webrtc.WebRTCCallService }: java.lang.IllegalArgumentException: com.antino.fitbasix.dev: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(30491): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

and after that device lost the connection.

**Comment by ghost** [comment]
@vartikaantino Hello

This is Nikolay from QuickBlox support.

As a workaround, now you can try fixing that by decreasing targetSdkVersion from 31 to 30 in the gradle (app level) file.

To investigate the issue further, please provide the following points:
1. Please let us know if there are any other steps to reproduce the issue and preconditions.
2. Is this issue intermittent or permanent?
3. Please try reproducing the issue on our Flutter debug sample:
https://github.com/QuickBlox/quickblox-flutter-samples
4. Please provide us with full REST + XMPP + WebRTC logs as an attachment in .txt format. There should be QB SDKs logs from application start till request and "wrong" response (error).
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/article/368-how-can-i-enable-quickblox-logs)
5. Please provide full crash logs.
6. Version of QuickBlox Flutter SDK.
7. Version of the platform (e.g. Android 11).
8. Devices in use (e.g. Redmi 8).
9. Flutter version.
10. Dart version.
