### ISSUE TITLE
When initialing web-Rtc this error is coming while starting service in only android 12 in flutter

### ISSUE THREAD

**Issue by rishabhOpenxcell** [QuickBlox/quickblox-flutter-sdk#52]
Console Log:

java.lang.RuntimeException: Unable to create service com.quickblox.quickblox_sdk.webrtc.WebRTCCallService: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10156, packageName = com.askfordr, attributionTag = null, token = android.os.BinderProxy@d2154b9, next = null }: getName
E/AndroidRuntime( 9237): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4540)
E/AndroidRuntime( 9237): 	at android.app.ActivityThread.access$1700(ActivityThread.java:256)
E/AndroidRuntime( 9237): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
E/AndroidRuntime( 9237): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 9237): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 9237): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 9237): 	at android.app.ActivityThread.main(ActivityThread.java:7842)
E/AndroidRuntime( 9237): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9237): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 9237): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime( 9237): Caused by: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10156, packageName = com.askfordr, attributionTag = null, token = android.os.BinderProxy@d2154b9, next = null }: getName
E/AndroidRuntime( 9237): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
E/AndroidRuntime( 9237): 	at android.os.Parcel.createException(Parcel.java:2409)
E/AndroidRuntime( 9237): 	at android.os.Parcel.readException(Parcel.java:2392)
E/AndroidRuntime( 9237): 	at android.os.Parcel.readException(Parcel.java:2334)
E/AndroidRuntime( 9237): 	at android.bluetooth.IBluetoothManager$Stub$Proxy.getName(IBluetoothManager.java:802)
E/AndroidRuntime( 9237): 	at android.bluetooth.BluetoothAdapter.getName(BluetoothAdapter.java:1297)
E/AndroidRuntime( 9237): 	at com.quickblox.quickblox_sdk.audio.QBAudioManager$QBBluetoothManager.logBluetoothAdapterInfo(QBAudioManager.java:904)
E/AndroidRuntime( 9237): 	at com.quickblox.quickblox_sdk.audio.QBAudioManager$QBBluetoothManager.start(QBAudioManager.java:785)
E/AndroidRuntime( 9237): 	at com.quickblox.quickblox_sdk.audio.QBAudioManager.start(QBAudioManager.java:258)
E/AndroidRuntime( 9237): 	at com.quickblox.quickblox_sdk.webrtc.WebRTCCallService.initAudioManager(WebRTCCallService.java:283)
E/AndroidRuntime( 9237): 	at com.quickblox.quickblox_sdk.webrtc.WebRTCCallService.onCreate(WebRTCCallService.java:126)
E/AndroidRuntime( 9237): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4527)
E/AndroidRuntime( 9237): 	... 9 more
E/AndroidRuntime( 9237): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime( 9237): 	at com.android.server.BluetoothManagerService.checkPermissionForDataDelivery(BluetoothManagerService.java:2941)
E/AndroidRuntime( 9237): 	at com.android.server.BluetoothManagerService.checkConnectPermissionForDataDelivery(BluetoothManagerService.java:2959)
E/AndroidRuntime( 9237): 	at com.android.server.BluetoothManagerService.getName(BluetoothManagerService.java:1736)
E/AndroidRuntime( 9237): 	at android.bluetooth.IBluetoothManager$Stub.onTransact(IBluetoothManager.java:380)
E/AndroidRuntime( 9237): 	at android.os.Binder.execTransactInternal(Binder.java:1179)
E/AndroidRuntime( 9237): 
D/TransportRuntime.SQLiteEventStore( 9237): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler( 9237): Scheduling upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) with jobId=1184313043 in 1000ms(Backend next call timestamp 1647493234227). Attempt 1
I/Process ( 9237): Sending signal. PID: 9237 SIG: 9

after that app crashes.

**Comment by ghost** [comment]
@rishabhOpenxcell Hello,

This is Nikolay from QuickBlox support.

Please check this thread:
https://stackoverflow.com/questions/67722950/android-12-new-bluetooth-permissions
