### ISSUE TITLE
Facing issue while create dialog in flutter

### ISSUE THREAD

**Issue by RutvijBhesaniya** [QuickBlox/quickblox-flutter-sdk#54]
E/MethodChannel#FlutterQBChatChannel(30863): Failed to handle method call
E/MethodChannel#FlutterQBChatChannel(30863): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.quickblox.auth.session.QBSessionParameters.getUserId()' on a null object reference
E/MethodChannel#FlutterQBChatChannel(30863): 	at com.quickblox.quickblox_sdk.chat.ChatModule.createDialog(ChatModule.java:482)
E/MethodChannel#FlutterQBChatChannel(30863): 	at com.quickblox.quickblox_sdk.chat.ChatModule.handleMethod(ChatModule.java:129)
E/MethodChannel#FlutterQBChatChannel(30863): 	at com.quickblox.quickblox_sdk.chat.-$$Lambda$DVgH6HdFVfXJ1jon6MQo8bSJBRA.onMethodCall(Unknown Source:2)
E/MethodChannel#FlutterQBChatChannel(30863): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#FlutterQBChatChannel(30863): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#FlutterQBChatChannel(30863): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#FlutterQBChatChannel(30863): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#FlutterQBChatChannel(30863): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#FlutterQBChatChannel(30863): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#FlutterQBChatChannel(30863): 	at android.os.Looper.loop(Looper.java:226)
E/MethodChannel#FlutterQBChatChannel(30863): 	at android.app.ActivityThread.main(ActivityThread.java:7178)
E/MethodChannel#FlutterQBChatChannel(30863): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterQBChatChannel(30863): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
E/MethodChannel#FlutterQBChatChannel(30863): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
I/flutter (30863): createdialogfailed=>Attempt to invoke virtual method 'int com.quickblox.auth.session.QBSessionParameters.getUserId()' on a null object reference

@QB-nikolay-zolotarov @QB-maksym-pidhorbunskyi

**Comment by ghost** [comment]
@RutvijBhesaniya Hello, please check this answer:
https://github.com/QuickBlox/quickblox-android-sdk/issues/544#issuecomment-365606509

**Comment by ghost** [comment]
@RutvijBhesaniya Did you solve the issue? Could you please provide more detailed information about the resolution?
