### ISSUE TITLE
Multliple user accounts not working in Flutter app

### ISSUE THREAD

**Issue by Ajaysinh1290** [QuickBlox/quickblox-flutter-sdk#55]
I'm creating an flutter app where one user have multliple accounts for chat and user can switch between their accounts. When i logout from one account and login in second account then the login is working but when i am retrieving old messages or sending any new messages then It is not using current logged in account it is using first account (Account that used to login first time when app starts) to send all that messages. 

Please solve this bug or Provide any solution for that.

Quickblox version :  ^0.6.5-beta
Flutter version : 2.8.1 
Dart version :  2.15.1      
Target Platfrom : both
Device in use : Real Device : Realme 8S 5g - Android 11 , Emulator :  Pixel-4 - Android 11

**Comment by AnsarAzees** [comment]
@Ajaysinh1290  Is this issue still exist? or do you have some workaround?
