### ISSUE TITLE
Token is required after relogin

### ISSUE THREAD

**Issue by vinceramcesoliveros** [QuickBlox/quickblox-flutter-sdk#56]
Hi. There's a problem when I log in and log out, then log in again.

After getting the quickBlox user ID, quickblox chat and password, the `QB.auth.login` will throw an error. I've looked through the docs and other SO questions and none have met the scenario I'm looking for the solution. I tried to use the `QB.auth.logout` right after I logged out and log in again using the same login method.

Here are the logs.
<details>
<summary>After relogin(login -> logout -> login)</summary>

```sh
[        ] D/QBASDK  (17026): *** RESPONSE *** 508dd2b8-85ff-40c4-8f35-163ed1618b7b ***
[        ] D/QBASDK  (17026): STATUS : 401
[        ] D/QBASDK  (17026): HEADERS
[        ] D/QBASDK  (17026):     x-request-id=Fu5Z_Yksh4tLAlUUPqmj
[        ] D/QBASDK  (17026):     X-Android-Selected-Protocol=http/1.1
[        ] D/QBASDK  (17026):     Server=nginx
[        ] D/QBASDK  (17026):     Connection=close
[        ] D/QBASDK  (17026):     X-Android-Response-Source=NETWORK 401
[        ] D/QBASDK  (17026):     X-Android-Sent-Millis=1652357057949
[        ] D/QBASDK  (17026):     cache-control=max-age=0, private, must-revalidate
[        ] D/QBASDK  (17026):     Content-Length=32
[        ] D/QBASDK  (17026):     X-Android-Received-Millis=1652357058533
[        ] D/QBASDK  (17026):     Date=Thu, 12 May 2022 12:04:18 GMT
[        ] D/QBASDK  (17026):     Content-Type=application/json; charset=utf-8
[        ] D/QBASDK  (17026): BODY
[        ] D/QBASDK  (17026):     '{"errors":["Token is required"]}'
[        ] D/QBASDK  (17026):
[   +6 ms] I/flutter (17026): PlatformException(Token is required, null, null, null)
```

</details>

**Comment by ghost** [comment]
Hello @vinceramcesoliveros , This is Nikolay from QuickBlox support.
Please try initializing the SDK before the second log in.
If the issue persists, please specify the SDK version and provide full REST + XMPP logs as an attachment in .txt format. There should be QB SDKs logs from application start till request and "wrong" response (error).
You can find out how to gather logs here: [Gathering logs guides - QuickBlox Help Center](https://help.quickblox.com/article/368-how-can-i-enable-quickblox-logs)
