### ISSUE TITLE
Constrain the RTCVideoView widget to fill its parent space

### ISSUE THREAD

**Issue by TusharGupta05** [QuickBlox/quickblox-flutter-sdk#57]
Hi! I wanted to know when will the native method for rtcvideoviewcontroller.scaleType get implemented?
Its current state is:
`private void scaleType(MethodCall methodCall, MethodChannel.Result result) {
        // TODO: need implement
}`
I basically want to constrain the RTCVideoView Widget to fill its  parent state but I couldn't find any working solution for that and the one that I found is not yet implemented.
Please help.

**Comment by ghost** [comment]
@TusharGupta05 Hello, we will consider implementing this method in the future, however, we cannot guarantee it for 100% at this moment because there were some incompatibilities.
