### ISSUE TITLE
the RTCVideoView position

### ISSUE THREAD

**Issue by roldanunne** [QuickBlox/quickblox-flutter-sdk#58]
Hi, 
Cannot set the position RTCVideoView in Stack for both local and remote video call. 
This is working before, but not this time?

Any thought?

**Comment by ghost** [comment]
@roldanunne Hello, please elaborate on the question

**Comment by roldanunne** [comment]
Here is my issue, I'm trying to align RTCVideoView inside the box, but it always on top. It ignore the Stack and Position to align it. Thanks

![Screenshot_2022-07-15-14-52-03-71_3f7c76c4f461f7544279d8b4c9e211ba](https://user-images.githubusercontent.com/4781184/179168503-af4f6c9d-1e62-4dd9-ab14-cbaa1a212ceb.jpg)

**Comment by roldanunne** [comment]
> QB-nikolay-zolotarov

Hi, any response to this issue?

**Comment by ghost** [comment]
@roldanunne Please clarify from which version of the Flutter SDK your implementation started working incorrectly.
You can use the version of the FlutterSDK with which it worked correctly.
Please note that the implementation of displaying video view is up to the client-side and does not relate to our SDK.

**Comment by berkansevimli** [comment]
> > QB-nikolay-zolotarov
> 
> Hi, any response to this issue?

Hello, did you fix it? I am getting same issue
