### ISSUE TITLE
Error PlatformException(XMPPError: bad-request - modify, null, null, null) on chat reconnect

### ISSUE THREAD

**Issue by yoseptara** [QuickBlox/quickblox-flutter-sdk#59]
Error : PlatformException(XMPPError: bad-request - modify, null, null, null)
![Screen Shot 2022-10-26 at 10 35 37](https://user-images.githubusercontent.com/49258329/197921048-8ed8d11e-267b-4492-ad0f-0094a7852023.png)

This error only occurs in release mode and not in debug mode.

dependencies:
  quickblox_sdk: ^0.8.0

How to reproduce :
1. Add didChangeAppLifecycleState on chat page (with disconnect and reconnect function)
Example : 
```
 void reconnect() async {
       await QB.chat.connect(qbUser!.id!, email);
       await QB.chat.joinDialog(dialogId);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if(chatDidChangeAppLifecycleState == false) {
      if (state == AppLifecycleState.resumed) {
      reconnect();
      } else {
       QB.chat.disconnect();
      }
    }

    super.didChangeAppLifecycleState(state);
  }
```

2. Run app with apk from (flutter build apk --release) or run with (flutter run --release)
3. Try minimize to disconnect and open app to reconnect

**Comment by vdovbnya-qb** [comment]
Hello @yoseptara 
Can you provide proguard file for Android?
Please reproduce this issue in our chat sample: https://github.com/QuickBlox/quickblox-flutter-samples/tree/master/chat_sample

**Comment by yoseptara** [comment]
> Hello @yoseptara Can you provide proguard file for Android? Please reproduce this issue in our chat sample: https://github.com/QuickBlox/quickblox-flutter-samples/tree/master/chat_sample

Thanks, I think I missed some rules in the proguard-rules file.

It worked after I made my proguard file exactly the same as the example : https://github.com/QuickBlox/quickblox-flutter-samples/tree/master/chat_sample
