### ISSUE TITLE
Retrieved lastMessageDateSent is int type?

### ISSUE THREAD

**Issue by austin-zy** [QuickBlox/quickblox-flutter-sdk#6]
After adding message into the dialog (Saved in history), I get this error when I call ```List<QBDialog> dialogs = await QB.chat.getDialogs();```

```
Unhandled Exception: type 'int' is not a subtype of type 'String'
#0      QBDialogMapper.mapToQBDialog (package:quickblox_sdk/mappers/qb_dialog_mapper.dart:25:16)
#1      Chat.getDialogs (package:quickblox_sdk/chat/module.dart:119:42)
<asynchronous suspension>
```

**Comment by akshayurs123** [comment]
I faced the same issue today while testing out the flutter SDK. Is there any work around for this issue?

```
E/flutter ( 5944): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'int' is not a subtype of type 'String'
E/flutter ( 5944): #0      QBDialogMapper.mapToQBDialog (package:quickblox_sdk/mappers/qb_dialog_mapper.dart:25:16)
E/flutter ( 5944): #1      Chat.getDialogs (package:quickblox_sdk/chat/module.dart:117:42)
```

**Comment by akshayurs123** [comment]
QuickBlox official website and documentation is not updated with latest versions. This issue got resolved for me after updating my version to 0.2.11-alpha found this version details on https://pub.dev/packages/quickblox_sdk
Hope it helps.

**Comment by akshayurs123** [comment]
Hi Team,

I am not able to load image attachment greater than 1 mb on the mobile
application. Is there any latest updated documentation for quickblox image
attachment ?

Thanks
Akshay

**Comment by kirillTolmachev** [comment]
Hello.
SDK doesn't have a limit for upload files.
Can you provide the name and version of the 3rd party library which you use for uploading files and logs from the application to check this behavior?

**Comment by akshayurs123** [comment]
Hi Kirill ,

Thanks for the response. Below is the code used for uploading the
attachment to quickblox

FilePickerResult result = await FilePicker.platform.pickFiles();
String fileUrl;
if (result != null) {
  File file = File(result.files.single.path);
  print("FILE PATH  " + file.uri.toString());
  fileUrl = file.uri.toString();
}

QBFile file = await QB.content.upload(fileUrl, public: true);

Version of quickblox: quickblox_sdk: ^0.3.9-alpha

Thanks
Akshay

**Comment by kirillTolmachev** [comment]
Can you provide the name of 3rd party library and version?
I mean: FilePicker

**Comment by akshayurs123** [comment]
Hi Kirill ,

The version of FilePicker is : file_picker: ^2.0.7

Thanks
Akshay
