### ISSUE TITLE
Vulnerable WebRTC versions on Google Play Console

### ISSUE THREAD

**Issue by TetrixGauss** [QuickBlox/quickblox-flutter-sdk#61]
Hello everyone! When i am trying to upload my application to Google play console i get that error: 

```
Vulnerable WebRTC versions 
Your application uses an inappropriate version of WebRTC, which contains security vulnerabilities.
```
On Apple Store there is no such a problem! 
I use the latest version of quickblox flutter plugin and i worked all this time! 
In previous uploads there was no problem! Is there any workaround on that?

**Comment by kirillTolmachev** [comment]
@TetrixGauss 
We know that is only a warning and google should accept your application. 
Please try to upload it.

**Comment by TetrixGauss** [comment]
@kirillTolmachev
I have tried multiple times but i get rejected due to that error.
<img width="772" alt="Screenshot 2023-01-11 at 2 23 50 PM" src="https://user-images.githubusercontent.com/28262732/211805601-8fe7d6b0-caff-4c3d-b198-51b62add2633.png">

**Comment by kirillTolmachev** [comment]
@TetrixGauss 
Thank you for providing information. In this case, we should update the WebRTC version and release a new version of Android SDK and then release a new version of Flutter SDK. 
Please wait for the new Flutter SDK version.

**Comment by TetrixGauss** [comment]
@kirillTolmachev Great! thank you! I am waiting for the new one!

**Comment by kirillTolmachev** [comment]
@TetrixGauss 
We have updated the webrtc version on android SDK side and now it is in testing.
Please wait for testing process and the new release for Flutter SDK.

**Comment by kirillTolmachev** [comment]
@TetrixGauss 
We have released a new version of Flutter QuickBlox 0.12.1 where we updated WebRTC version.
Please try to release your application.

**Comment by TetrixGauss** [comment]
@kirillTolmachev you are the man!!! I am going to test it!

**Comment by kirillTolmachev** [comment]
@TetrixGauss 
Please provide feedback. 
Has your issue been resolved?

**Comment by TetrixGauss** [comment]
@kirillTolmachev I haven't get any errors from Google Play Console, so i assume that everything is alright!
