### ISSUE TITLE
Exception while creating subscription with FCM token on IOS only, same code works perfectly on Android

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [QuickBlox/quickblox-flutter-sdk#63]
Hey, I've been trying to solve this problem by going through the Quickblox Flutter documentation but unfortunately I've not been able to resolve this issue. Following is the code I'm using to create a subscription using the FCM code along with the error log:

*********************************************************
Create subscription code:

firebaseMessaging.getToken().then((token) async {
      logger.w('[FCM] token => $token');
      print(token);
      await registerFCMToken(token);
});

 Future<void> registerFCMToken(String? token) async {
    try {
      List<QBSubscription?> subscriptions =
          await QB.subscriptions.create(token!, QBPushChannelNames.GCM);
    } catch (exception) {
      logger.d("Exception during fcm token registration$exception");
    }
}

********************************************************* 

********************************************************* 
Error logs: 

parameters: {
    device =     {
        platform = ios;
        udid = " **** ";  ( device udid is printed over here )  
    };
    "notification_channels" = gcm;
    "push_token" =     {
        "bundle_identifier" = "com.example.app";
        "client_identification_sequence" = 0c070d0e0e0f07080aa91b0f090906a8a8050d0bab0dc70f0a6c0b5e0a0be80ddf0d0f06210d7dcfe80a05040c043e05;
        environment = development;
    };
}
[ChatService]: RCV: <iq xmlns="jabber:client" to="136756387-99709@chat.quickblox.com/167EEE61-6749-41A3-8B62-D67304AEABCE" type="result" id="B54E4F4D-35C9-4660-B51F-8705542078BA"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><jid>136756387-99709@chat.quickblox.com/167EEE61-6749-41A3-8B62-D67304AEABCE</jid></bind></iq>
[QBCore]: Response[4]
headers: {
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-cache";
    "Content-Length" = 60;
    "Content-Type" = "application/json; charset=utf-8";
    Date = "Thu, 16 Feb 2023 05:28:28 GMT";
    Duration = "0.443542";
    Server = QuickBlox;
    "Strict-Transport-Security" = "max-age=0; includeSubDomains";
    "access-control-expose-headers" = "QB-Token-ExpirationDate";
    "content-security-policy" = "default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data: www.google-analytics.com; object-src 'none'; script-src 'self' https: 'unsafe-eval' 'unsafe-inline' www.google-analytics.com; style-src 'self' https: 'unsafe-inline'";
    "qb-token-expirationdate" = "2023-02-16 07:28:28 UTC";
    "quickblox-rest-api-version" = "0.1.1";
    "referrer-policy" = "strict-origin-when-cross-origin";
    "x-content-type-options" = nosniff;
    "x-download-options" = noopen;
    "x-frame-options" = SAMEORIGIN;
    "x-permitted-cross-domain-policies" = none;
    "x-request-id" = "0bad250a-b0c0-47b9-a88d-a9f0f5a3731f";
    "x-runtime" = "0.039248";
    "x-xss-protection" = "1; mode=block";
}
error: Request failed: client error (422)
reasons: {
    errors =     {
        "client_identification_sequence" =         (
            "is invalid"
        );
    };
}
flutter: ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
flutter: │ #0   QuickBloxVoipService.registerFCMToken
quickblox_voip_service.dart:426
flutter: │ #1   <asynchronous suspension>
flutter: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
flutter: │ 🐛 Exception during fcm token registrationPlatformException(422
flutter: │ 🐛 "client_identification_sequence" is invalid
flutter: │ 🐛 , null, Request failed: client error (422), null)
flutter: └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Do I have to register a different token (Pushkit) for IOS?

**Comment by AbdurrehmanSubhani** [comment]
I've uploaded the Universal (Sandbox & Production & VoIP) SSL certificate to the QuickBlox push notification as well

**Comment by IlliaChemolosov** [comment]
Hello @AbdurrehmanSubhani !
it's Illia from QuickBlox.

We edited the code snippet that describes the [push notification subscription process](https://docs.quickblox.com/docs/flutter-push-notifications#subscribe-to-push-notifications).

Please, use the code below to enable iOS push notifications when creating a subscription.
```
String channelName = "";
String? token  = "";
try {
  if (Platform.isAndroid) {
    token = await FirebaseMessaging.instance.getToken();
    channelName = QBPushChannelNames.GCM;
  } else if (Platform.isIOS) {
    token = await FirebaseMessaging.instance.getAPNSToken();
    channelName = QBPushChannelNames.APNS;
  }
  await QB.subscriptions.create(token!,channelName);
} on PlatformException catch (e) {
  // Some error occurred, look at the exception message for more detai
}
```

**Comment by AbdurrehmanSubhani** [comment]
> Hello @AbdurrehmanSubhani ! it's Illia from QuickBlox.
> 
> We edited the code snippet that describes the [push notification subscription process](https://docs.quickblox.com/docs/flutter-push-notifications#subscribe-to-push-notifications).
> 
> Please, use the code below to enable iOS push notifications when creating a subscription.
> 
> ```
> String channelName = "";
> String? token  = "";
> try {
>   if (Platform.isAndroid) {
>     token = await FirebaseMessaging.instance.getToken();
>     channelName = QBPushChannelNames.GCM;
>   } else if (Platform.isIOS) {
>     token = await FirebaseMessaging.instance.getAPNSToken();
>     channelName = QBPushChannelNames.APNS;
>   }
>   await QB.subscriptions.create(token!,channelName);
> } on PlatformException catch (e) {
>   // Some error occurred, look at the exception message for more detai
> }
> ```

This provided solution works
Thanks!

**Comment by minoesteban** [comment]
Can you confirm if this approach still does not work on iOS simulator? I have implemented this exactly as described and still get `client_identification_sequence is invalid`. 

I guess APNS token format for simulator is different in some way? Or QB does not support it?
