### ISSUE TITLE
How to handle an expired session token using QBAuthEvents.SESSION_EXPIRED

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [QuickBlox/quickblox-flutter-sdk#65]
Hey, what's the best way to handle an expired user session token if the auth event subscriber receives the event QBAuthEvents.SESSION_EXPIRED. (by the best way, what i mean is that, what are the steps that need to be taken in order to create a new valid user session token, idealy which do not require a user to re-enter their login credentails and login into quickblox again)
Any help would be much appreciated. Thanks!

**Comment by kirillTolmachev** [comment]
Hello @AbdurrehmanSubhani 
If you set a token from your side:
**QB.auth.startSessionWithToken(QUICKBLOX_TOKEN);**
then you need to set a new token after you will have received event QBAuthEvents.SESSION_EXPIRED.
if you set a token for user session then you don't need to invoke login but if you set application token you need to invoke login method to upgrade application session to user session.
You can read more details in documentation by a link [Application vs User session token](https://docs.quickblox.com/reference/authentication#application-vs-user-session-token)

**Comment by AbdurrehmanSubhani** [comment]
Understood, thanks!
