### ISSUE TITLE
Subscription created more than one time

### ISSUE THREAD

**Issue by jeetbv** [QuickBlox/quickblox-flutter-sdk#67]
Hello There,
I am facing the issue of a subscription created multiple times in the quick box dashboard. let me explain when I try to log in with the email and password, the dashboard creates the create one push subscription with the FCM and UDID, after I just uninstall the application and try to login then it creates one more push subscription. so I need to fix these things.
I check with the android application. iOS has not had an issue with these things. 

So is there any way to not create the duplicate push token as well if created then how we can delete through with the code?

**Comment by sshaforenkoqb** [comment]
Hello @jeetbv,
Could you please clarify the following points:
- Are you using a cloud or enterprise plan?
- What SDK version are you using?

As a temporary solution you can disable automatic subscription and create subscriptions manually https://docs.quickblox.com/docs/android-push-notifications#manual-push-subscription

**Comment by jeetbv** [comment]
Hello @sshaforenkoqb,

Are you using a cloud or enterprise plan? - Starter plan
What SDK version are you using? - quickblox_sdk-0.7.1.

**Comment by jeetbv** [comment]
Hello @sshaforenkoqb 
First which step do I need to do and how to disable the subscription can you please help me to fixes these things?
 
We have a flutter application and we are using the flutter application with the native code to integrate the video call. android and iOS both have different code.

**Comment by sshaforenkoqb** [comment]
Got it, thought you are using Android SDK because issue were created in Android SDK repo.
There is no automatic subscription in the Flutter SDK, the bug you are reported is a known issue and will be fixed on backend in nearest time. Please note that fix will work only for flutter SDK v0.12.1 and higher.
As a temporary solution:
1. Update to the latest SDK(v.0.12.4). Changelog and migration guide can be found [here](https://pub.dev/packages/quickblox_sdk/changelog).
2.Before you are creating a subscription add next functionality:
`// Get all subscriptions
List<QBSubscription?> subscriptions = await QB.subscriptions.get();
// Iterate through all subscriptions and remove
subscriptions.forEach((subscription) => {
    await QB.subscriptions.remove(subscription!.id!);
 });
`

**Comment by jeetbv** [comment]
How i know the subscription was deleted for the same user who is logged user ?

**Comment by sshaforenkoqb** [comment]
You will receive list of subscriptions only for this user.

**Comment by jeetbv** [comment]
-"The call service is ready " notification hide to follow below steps :-
step1 - updateNotification() - method comment in WebRTCCallService.java and ConferenceCallService.java
step2 - comment lines...

<string name="webrtc_call_service_notification_title">The call service is ready</string>
<string name="webrtc_call_service_notification_text">Quickblox</string>

<string name="conference_call_service_notification_title">The call service is ready</string>
<string name="conference_call_service_notification_text">Quickblox</string>


1. We add the dependency as a module and try to comment, on the code but still "The call service is ready " message comes. 
2. Overlay permission is compulsory to get the call? if the user does not allow this permission call not connected?

**Comment by sshaforenkoqb** [comment]
Regarding your second question, the overlay permission is required on Android devices to display a floating incoming call notification on top of other apps. If the user does not grant this permission, the incoming call notification will not be displayed and the call will be missed.
And regarding "The call service is ready" notification, in current version of SDK it will be shown permanently, there is no way to remove it.
