### ISSUE TITLE
Issue with voip notification in app, when we put app for few minutes to idle condition then , call stop coming in flutter technology

### ISSUE THREAD

**Issue by neeraj92144** [QuickBlox/quickblox-flutter-sdk#70]
I am sharing the two screenshots also one for sending normal notification that sent succesfully to 4 ihone devices

and Another screenshot of sending voip notification that are failing , Please have a look.

Also, I have a log of notifications, you can check also where it is saying 

error_description = DeviceTokenNotForTopic

{"notification":{"id":66755877,"badge":null,"device_token":"dcd399a91357cf4733e4f128fb13803b5c023e089fb169e92745d8daf9d0fe92","sound":"default","alert":"testing","data":{"headers":{"apns-topic":"smart.ask.expert.voip","apns-expiration":0}},"expiry":86400,"delivered":false,"delivered_at":null,"failed":true,"failed_at":"2023-04-03T16:16:14+00:00","fail_after":"2023-04-03T17:16:14+00:00","retries":0,"error_code":400,"error_description":"DeviceTokenNotForTopic","deliver_after":null,"alert_is_json":null,"sound_is_json":null,"app_id":87624,"collapse_key":null,"delay_while_idle":null,"registration_ids":null,"uri":null,"priority":null,"url_args":null,"category":null,"content_available":false,"dry_run":false,"mutable_content":false,"notification":null,"thread_id":null,"type":"Rpush::Client::Redis::Apns::Notification","event_id":38859666,"event_date":"2023-04-03T16:16:14+00:00"},"log":[{"device_token":"dcd399a91357cf4733e4f128fb13803b5c023e089fb169e92745d8daf9d0fe92","delivered_at":null,"failed_at":"2023-04-03T16:16:14+00:00","error_code":400,"error_description":"DeviceTokenNotForTopic"},{"device_token":"0ab2995752665856d0352f2a9c791b832056b040e7bb5a3e6ef4f574006092fc","delivered_at":null,"failed_at":"2023-04-03T16:16:14+00:00","error_code":400,"error_description":"DeviceTokenNotForTopic"},{"device_token":"09e8cc9e56060da85b2cf0a21663a18ebdeea39852d157d7a317a903d1ec3133","delivered_at":null,"failed_at":"2023-04-03T16:16:14+00:00","error_code":400,"error_description":"DeviceTokenNotForTopic"},{"device_token":"6125a5a26e8fb01c7ada08f38bdd418cbc86a101d4948c70667d7d7f0e607497","delivered_at":null,"failed_at":"2023-04-03T16:16:14+00:00","error_code":400,"error_description":"DeviceTokenNotForTopic"}]}
![image_2023_04_03T16_18_14_789Z](https://user-images.githubusercontent.com/26308047/229571496-a55bdce0-ac81-445c-a588-7bc4e6e06439.png)
![image_2023_04_03T16_18_27_696Z](https://user-images.githubusercontent.com/26308047/229571501-2e208672-51e9-4d91-b55c-6e7a1cdcce28.png)

**Comment by neeraj92144** [comment]
![Screen Shot 2023-04-03 at 10 02 05 PM](https://user-images.githubusercontent.com/26308047/229571694-96438bad-ddd9-4c8c-9d82-e2865cfefc2e.png)

**Comment by neeraj92144** [comment]
Hi, Does Anyone have a solution to my problem

**Comment by sshaforenkoqb** [comment]
Hi @neeraj92144, could you please also share logs for successfully delivered notifications?

**Comment by neeraj92144** [comment]
yes succefully message deliver to ios app as follows ->

{"notification":{"id":66771697,"badge":null,"device_token":"09e8cc9e56060da85b2cf0a21663a18ebdeea39852d157d7a317a903d1ec3133","sound":"default","alert":"Testing - Ignore 5","data":{"headers":{"apns-topic":"smart.ask.expert","apns-push-type":"alert","apns-expiration":1680788362}},"expiry":86400,"delivered":true,"delivered_at":"2023-04-05T13:39:22+00:00","failed":null,"failed_at":null,"fail_after":"2023-04-05T14:39:22+00:00","retries":0,"error_code":null,"error_description":null,"deliver_after":null,"alert_is_json":null,"sound_is_json":null,"app_id":87624,"collapse_key":null,"delay_while_idle":null,"registration_ids":null,"uri":null,"priority":null,"url_args":null,"category":null,"content_available":false,"dry_run":false,"mutable_content":false,"notification":null,"thread_id":null,"type":"Rpush::Client::Redis::Apns::Notification","event_id":38861890,"event_date":"2023-04-05T13:39:22+00:00"},"log":[{"device_token":"09e8cc9e56060da85b2cf0a21663a18ebdeea39852d157d7a317a903d1ec3133","delivered_at":"2023-04-05T13:39:22+00:00","failed_at":null,"error_code":null,"error_description":null}]}

**Comment by neeraj92144** [comment]
yes, successfully message deliver to the Android app as follows ->

{"notification":{"id":66771713,"badge":null,"device_token":null,"sound":"default","alert":null,"data":{"message":"Testing - Ignore - 6","collapse_key":"event38861904"},"expiry":86400,"delivered":false,"delivered_at":null,"failed":true,"failed_at":"2023-04-05T13:44:11+00:00","fail_after":"2023-04-05T14:44:10+00:00","retries":0,"error_code":null,"error_description":"Unable to deliver notification 66771713, received error (Failed to deliver to recipients 0, 1, 2, 3, 5. Errors: NotRegistered, NotRegistered, NotRegistered, NotRegistered, NotRegistered.)","deliver_after":null,"alert_is_json":null,"sound_is_json":null,"app_id":87074,"collapse_key":null,"delay_while_idle":false,"registration_ids":["e5Kb5TACR-Wl9isKjUURhg:APA91bHi7wOVXGf5pSkxASZYre4TEYoxQyju4LBeKQj8GSr3fUGKSk5iAYenx8Ztef0Ko8HB0dUvYKoHCrORhcj_5WsOtAFZp-cAAO4bLHpr2QCUlCLk9YGzqC7T6KMOaCSzaerhkTiL","ctzfpXgyT9SgHF3jfcZuks:APA91bHNQjPD7isni9ciVbsCEjSAh_0L7qJx-WrkI-6cuHjVJT8bgCSLkc75Eo5MNvnFkkKmGiUUWmpql9EtgS10x3zriaj-KdlX5PP6DhLzzr1MHiVJMixWDinVMyPs-9zssWaONLbV","fKQic5DaRkOLvIzvwQnSRc:APA91bGnlICvM_DHMlMI9rbGLUbwMMRySeX3XNvm63Gr7y2dK4O_Zxy8XqGT_CpO6zwZBSoq-EO9BuNrHAIfp9p5oSa30U4GHX39daYn_9akkNkYe7mhzjxzQWpT7muo6-8KnDbhX8BG","dw20QYaVQPGVjfSXdYwqx8:APA91bFnN4nqJXpzrYlNkD9dvcl25d9f7Y5fseiojVcaHiIC95EEd519vOrwmmkzjAgiPxGhfHai4PJ7Tp0hhroCyqFnSiBXaMHj4KTORs6j-irZupWpMP3o9cJC1OioKhH5rsiu4hFY","fb2sNN3zSze8HaGf6Dwc3j:APA91bEM84ub81FV04gEEpopv055DA2hhSiKw1xG_ccP2n8bz_lLZQI0rsY2tOLseh1kGayua-x9xrdCpAet0iZdXqp7Fwh2oyZXRCsXFS9vcQ1FLd8PV-Ai6cKaNlJ4m85Nr0SxFoZ7","ccJNLbIKR1Wso06N_Cqyj3:APA91bEt_UdfF41lllH6EU8UXwEpUct-qRVR7CKcYJnPnihq8BFXOcCWdbu8TX7UI4tLiXFAFDJK8VvdL0V616-P8qs6MJ4yB9LdkIPgVG7Uu1cXFveHsAhLD7PT4LcgSgRQiEfstzVQ"],"uri":null,"priority":10,"url_args":null,"category":null,"content_available":false,"dry_run":false,"mutable_content":false,"notification":null,"thread_id":null,"type":"Rpush::Client::Redis::Fcm::Notification","event_id":38861904,"event_date":"2023-04-05T13:44:10+00:00"},"log":[{"device_token":null,"delivered_at":null,"failed_at":"2023-04-05T13:44:11+00:00","error_code":null,"error_description":"Unable to deliver notification 66771713, received error (Failed to deliver to recipients 0, 1, 2, 3, 5. Errors: NotRegistered, NotRegistered, NotRegistered, NotRegistered, NotRegistered.)"}]}

**Comment by sshaforenkoqb** [comment]
To fix this issue:

1. Remove all ios certificates from your admin panel for the app
2. Upload the Universal (sandbox & production & voip) certificate([how to create](https://docs.quickblox.com/docs/ios-push-notifications#create-universal-apns-certificate))

**Comment by neeraj92144** [comment]
If I do the above fixes, it is for the ios platform. what about the Android platform. Becasue issue are same for android and ios , even if I remove certicate and all then will it also resovle for android also. 

From the above step , will I able to get VOIP notifcation and both platform

**Comment by Neerajdevco** [comment]
Also, there is a certificate by the name of VOIP certificate where we will upload that certificate in your quick block section as there is only one section for only

**Comment by Neerajdevco** [comment]
![Screen Shot 2023-04-05 at 8 07 03 PM](https://user-images.githubusercontent.com/94952512/230114831-19e8c1b2-921f-4efd-b71a-e563612d673a.png)

**Comment by neeraj92144** [comment]
Also, there is a certificate by the name of VOIP certificate where we will upload that certificate in your quick block section as there is only one section for only

**Comment by neeraj92144** [comment]
![Screen Shot 2023-04-05 at 8 07 03 PM](https://user-images.githubusercontent.com/26308047/230115931-c34faf1f-fca8-412e-9c64-bb531e96857a.png)

**Comment by neeraj92144** [comment]
![Screen Shot 2023-04-05 at 8](https://user-images.githubusercontent.com/26308047/230116620-46332ebe-062a-4167-b945-5f639e6e1b45.png)
![Screen Shot 2023-04-05 at 8 11 26 PM](https://user-images.githubusercontent.com/26308047/230116654-7ec1ccf5-c195-4b36-b63a-72c1e73abdda.png)

**Comment by neeraj92144** [comment]
Hi, can you please reply to above mention?

**Comment by sshaforenkoqb** [comment]
Hi @neeraj92144,

> Also, there is a certificate by the name of VOIP certificate where we will upload that certificate in your quick block section as there is only one section for only

Use Universal certificate only, no need to add an additional certificate.

> If I do the above fixes, it is for the ios platform. what about the Android platform. Becasue issue are same for android and ios , even if I remove certicate and all then will it also resovle for android also.
> 
> From the above step , will I able to get VOIP notifcation and both platform

Please check that for Android users you have subscriptions.
For Android there is no separate type of notifications as for iOS, so to wake up an Android device you should use regular push notifications with pushType QBNotificationPushTypes.GCM

**Comment by neeraj92144** [comment]
So, should we manually needed to send a notification when someone calls someone, or it will handle my quick block automatically, I see after some time quick block lost control over the device and is unable to detect whether the call is coming or not.

**Comment by neeraj92144** [comment]
If some sort of Firebase remote notification would have sent then we could have get the notification and request for further to the call to the user

**Comment by sshaforenkoqb** [comment]
Hi @neeraj92144, a push notification should be sent from the application before you are doing the call.
So you will have the next flow:
- Send push notification(VoIP for ios and regular for Android).
- Make a call

If the callee application is in background for iOS you should show CallKit screen with incoming calls, and for Android you can show a regular notification or use ConnectionService to show incoming call. You can take a look at [callkeep](https://pub.dev/packages/callkeep) library
