### ISSUE TITLE
Did not get offline messages when any user offline and get message

### ISSUE THREAD

**Issue by Enayat01** [QuickBlox/quickblox-flutter-sdk#72]
I have add listener in main function but did not get the offline messages
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  runApp(const MyApp());
}

**Comment by kirillTolmachev** [comment]
Hello @Enayat01 
Your code missing some important steps. 
Please check our article about "how to add push notifications to flutter" [ARTICLE LINK](https://quickblox.com/blog/how-to-add-push-notifications-to-your-flutter-app-on-android/)

Also, please double-check that you correctly set up Firebase messaging like [HERE](https://quickblox.com/blog/how-to-get-your-android-app-ready-to-add-push-notifications/)
If provided steps won't help you, then please check additional steps:
1. Try to send a push message directly from the Firebase console to your device.
2. Try to send a push message from Quickblox Admin Panel to your device. 
3. Check that in admin panel you have subscriptions. You can see subscriptions for a selected user on the bottom of screen like in attached image.

![subscription](https://user-images.githubusercontent.com/41300382/230627436-ec5a26c8-b5ea-46b3-8ca4-69e8d64f5b91.png)

In most cases, these steps will resolve your issue.
