### ISSUE TITLE
Call takes longer time to get accepted even after verifying as connected to chat through QB.chat.isConnected()

### ISSUE THREAD

**Issue by AbdurrehmanSubhani** [QuickBlox/quickblox-flutter-sdk#73]
Scenario:

I receive a call through a VoIP APNS push for IOS voice calling, since the application is terminated, we have to initialise the sdk before accepting the call.
In my app flow, the initialisation process for Quickblox SDK starts just as the call is displayed through Callkit, the initialisation takes around 3-4 seconds after which i call the Call accept function right after initialisation.

With this flow the call either gets accepted or the sdk fails to accept the call and this occurs randomly.

However, i added a delay timer for 5 seconds after the sdk has been initialised after which i execute the Call accept function. With this delay the call gets accepted every-time, therefore i assume the sdk is still not in ready state to accept the call even after getting 'true' response from QB.chat.isConnected() function for a few seconds.

Is there another method that i should use to verify the sdk is ready to accept a call or should the chat.isConnected() function only return 'true' when the sdk is ready to accept a call. Any help would be much appreciated, Thanks!

**Comment by sshaforenkoqb** [comment]
Hi @AbdurrehmanSubhani,
VoIP notification used only to wake up your application, then you need to init QB SDK, log in, connect to chat, receive incoming call event. After you received incoming call event you can accept the call, before this QB SDK doesn't know about the call.

**Comment by AbdurrehmanSubhani** [comment]
I totally agree!
The problem arises when a user accepts a call before the sdk is initialised, say for example i received a callkit call notification alert and i accepted the call within 1 second, until then the sdk has not been initialised. 
I need assistance on how to wait for the sdk to be initialised before i can call the accept call function (when the sdk is fully initialised).
Currently i run a while loop until i receive a sdk initialised event, once the sdk initialised event is fired (after checking chat.isConnected() ) i wait through Future.delayed() for 5 seconds (issue: if i execute accept function within 1-2 seconds of chat.isConnected(), the call does not get accepted) and then call the accept button.

**Comment by AbdurrehmanSubhani** [comment]
Sorry wrong tap 😅

**Comment by sshaforenko** [comment]
You can wait for QB.webrtc.EVENT_TYPE.CALL and if user previously tapped accept button accept the call automatically.

**Comment by fAns1k** [comment]
@sshaforenko @sshaforenkoqb is there a way to speed up the initialization phrase after the kill state? or manually request data about a new call to update QB core. 

In my case, it takes around 5-10 seconds to connect to the audio/video call which is long if we compare it with regular rtc signalling with `QB.webrtc.EVENT_TYPE.CALL`.
Also, if you put an app in the background (it's in the widget tree) and call `QB.chat.disconnect()` in `dispose` method then call from 2nd account, it opens the app -> connect to chat -> wait for `QB.webrtc.EVENT_TYPE.CALL` the same amount of time as it's from the kill state. 

So, when you reconnect to the chat it re-initialize the signalling system it takes same 5-10 seconds to pick everything up.

Please share your thoughts, my app requires 1-2 seconds to connect to the call from background and kill state as well.

Thank you.

**Comment by sshaforenkoqb** [comment]
Hi @fAns1k, unfortunately at this moment there is no way to speedup connection process.
