### ISSUE TITLE
Error in IOS Video call the camera video is not showing

### ISSUE THREAD

**Issue by afgprogrammer** [QuickBlox/quickblox-flutter-sdk#76]
I am trying to build a video/audio call application but I have faced with difficulties in IOS, I am getting this error when I accept a video call in an IOS 17 device also in IOS simulator it's not showing the local camera video of the user. The application in a real device will go to pause mode. Here is an screenshot of xCode. I did not test it on other IOS devices or any other IOS versions but it does work fine in android.

btw, the call is between web sdk and flutter ios.

<img width="1512" alt="Screenshot 2023-11-28 at 11 39 37 AM" src="https://github.com/QuickBlox/quickblox-flutter-sdk/assets/17293422/3ed0a9f2-21a4-4f2b-b364-898b6cb42c2f">

**Comment by kirillTolmachev** [comment]
Hello @afgprogrammer 
Thank you for providing information.
Could you please check the same behavior in a real device with an IPA file? I mean build an IPA file and upload it to a device **without** a USB connection device to pc.
