### ISSUE TITLE
Custom Endpoint Not working 

### ISSUE THREAD

**Issue by VimarsSpaceo** [QuickBlox/quickblox-flutter-sdk#77]
I have quickblox enterprice plan and I am using custom apiEndPoint and chatEndpoint 
everything was working fine but recently custom endpoints not working, every quickblox call fires through the default url 
and getting 404 error also it is showing warning about "There is no information about chat server endpoint, use the default one."
![Screenshot 2023-12-01 at 4 20 23 PM](https://github.com/QuickBlox/quickblox-flutter-sdk/assets/152607141/bb5bc66c-f5cb-4771-a069-044af462e065)

**Comment by kirillTolmachev** [comment]
Hello @VimarsSpaceo 

The provided logs show that in SDK custom endpoints were not set.
To understand where the is problem we need to collect some additional data.
Did you add any changes to your code before the problem appeared?
Did you clear the application data in the application settings?

**Comment by VimarsSpaceo** [comment]
Yes, I have not done any changes before 
in my code set first quickblox init method called and I have passed all the param in to that with api endpoint and chat end point after init call i have a qb login call and in this login call api getting fail with given log 

and I can see in log the api url is default url not custom which is given earlier and also worked earlier 
here is the api response log 

I/flutter (30403): user : Instance of 'People'
D/QBASDK  (30403): Restored custom endpoints. ApiEndpoint: , ChatEndpoint: . lastUpdateTime: Thu Jan 01 05:30:00 GMT+05:30 1970
D/QBASDK  (30403): DEVICE_ID = 00000000-4eeb-d7ed-ffff-ffffa80019d3
D/QBASDK  (30403): There is no information about chat server endpoint, use the default one.
D/QBASDK  (30403): There is no information about chat server endpoint, use the default one.
[GETX] GOING TO ROUTE /dashboard_page
[GETX] REMOVING ROUTE /login_page
[GETX] Instance "DashboardController" has been created
[GETX] Instance "DashboardController" has been initialized
[GETX] Instance "HomeController" has been created
I/flutter (30403): user : Instance of 'People'
[GETX] Instance "HomeController" has been initialized
D/EGL_emulation(30403): app_time_stats: avg=10.50ms min=2.34ms max=95.69ms count=36
D/QBASDK  (30403): =========================================================
D/QBASDK  (30403): === REQUEST ==== 7e2dbcc7-9d9a-4d0f-bb7e-eff12856df33 ===
D/QBASDK  (30403): REQUEST
D/QBASDK  (30403):     GET https://api.quickblox.com/account_settings.json
D/QBASDK  (30403): HEADERS
D/QBASDK  (30403):     QB-Account-Key=ack_1bhLYZK6ssySh-T62gsE
D/QBASDK  (30403): PARAMETERS
D/QBASDK  (30403): 
D/QBASDK  (30403): INLINE
D/QBASDK  (30403):     GET https://api.quickblox.com/account_settings.json
I/flutter (30403): getDistinctId : 256
[GETX] "LoginController" onDelete() called
[GETX] "LoginController" deleted from memory
D/EGL_emulation(30403): app_time_stats: avg=17.48ms min=2.44ms max=196.87ms count=35
D/QBASDK  (30403): *********************************************************
D/QBASDK  (30403): *** RESPONSE *** 7e2dbcc7-9d9a-4d0f-bb7e-eff12856df33 ***
D/QBASDK  (30403): STATUS : 404 
D/QBASDK  (30403): HEADERS
D/QBASDK  (30403):     Access-Control-Allow-Origin=*
D/QBASDK  (30403):     Cache-Control=no-cache
D/QBASDK  (30403):     Connection=close
D/QBASDK  (30403):     Content-Length=0
D/QBASDK  (30403):     Content-Security-Policy=default-src 'self' https:; font-src 'self' https: data:; img-src 'self' https: data: www.google-analytics.com; object-src 'none'; script-src 'self' https: 'unsafe-eval' 'unsafe-inline' www.google-analytics.com; style-src 'self' https: 'unsafe-inline'
D/QBASDK  (30403):     Content-Type=application/json
D/QBASDK  (30403):     Date=Fri, 01 Dec 2023 12:14:24 GMT
D/QBASDK  (30403):     QuickBlox-REST-API-Version=0.1.1
D/QBASDK  (30403):     Referrer-Policy=strict-origin-when-cross-origin
D/QBASDK  (30403):     Server=QuickBlox
D/QBASDK  (30403):     Strict-Transport-Security=max-age=31556952; includeSubDomains; preloadmax-age=31536000; includeSubDomains
D/QBASDK  (30403):     X-Android-Received-Millis=1701432860306
D/QBASDK  (30403):     X-Android-Response-Source=NETWORK 404
D/QBASDK  (30403):     X-Android-Selected-Protocol=http/1.1
D/QBASDK  (30403):     X-Android-Sent-Millis=1701432860000
D/QBASDK  (30403):     X-Content-Type-Options=nosniff
D/QBASDK  (30403):     X-Download-Options=noopen
D/QBASDK  (30403):     X-Frame-Options=SAMEORIGIN
D/QBASDK  (30403):     X-Permitted-Cross-Domain-Policies=none
D/QBASDK  (30403):     X-Request-Id=2a407fc6-ddc0-4478-b52a-79d855d6106b
D/QBASDK  (30403):     X-Runtime=0.007739
D/QBASDK  (30403):     X-XSS-Protection=1; mode=block
D/QBASDK  (30403): BODY
D/QBASDK  (30403):     ''
D/QBASDK  (30403): 
D/QBASDK  (30403): Synchronizing account settings failed
E/flutter (30403): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s) (onError): The error handler of Future.catchError must return a value of the future's type
E/flutter (30403): #0      _FutureListener.handleError (dart:async/future_impl.dart:181:7)
E/flutter (30403): #1      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796:47)
E/flutter (30403): #2      Future._propagateToListeners (dart:async/future_impl.dart:817:13)
E/flutter (30403): #3      Future._completeError (dart:async/future_impl.dart:592:5)
E/flutter (30403): #4      _RootZone.runBinary (dart:async/zone.dart:1666:54)
E/flutter (30403): #5      _FutureListener.handleError (dart:async/future_impl.dart:162:22)
E/flutter (30403): #6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:796:47)
E/flutter (30403): #7      Future._propagateToListeners (dart:async/future_impl.dart:817:13)
E/flutter (30403): #8      Future._completeError (dart:async/future_impl.dart:592:5)
E/flutter (30403): <asynchronous suspension>
E/flutter (30403): 





here is my code in flutter :- 



  AppClass().showQuickBloxLoading(true);
      await QB.settings.init(APP_ID, AUTH_KEY, AUTH_SECRET, ACCOUNT_KEY,apiEndpoint: qbApiEndPoint,chatEndpoint: qbChatEndPoint).catchError((_){});
      AppClass().addQuickBloxEvent('QB-settings');

      await QB.auth.logout();
      AppClass().addQuickBloxEvent('QB-logout');
      result = await QB.auth.login(userEmail, qbPassword).catchError((_){});
      AppClass().addQuickBloxEvent('QB-login');
      qbUser = result?.qbUser;
      qbSession = result?.qbSession;

      debugPrint('initClient :  initClientQB');
      await cancelSubscriptions();





also noticed that this issue only happens to Android device, in IOS it is working fine

**Comment by kirillTolmachev** [comment]
Thank you @VimarsSpaceo for providing information.

Now, I think we have enough information to clarify the problem.
From your side please double check that you input the correct **account key** value `ack_1bhLYZK6ssySh-T62gsE`
You can find the account key value in your QuickBlox dashboard on general page of your Application.

From my side I will try to reproduce the problem and come back.

**Comment by VimarsSpaceo** [comment]
Account key is perfect from my side

**Comment by quickblox-custom-development** [comment]
Hi @VimarsSpaceo ,

Our Dev Team needs to know some sensitive details about your account. 
Please contact our Support Team at https://help.quickblox.com/conversation/new and send in your message link to this GitHub issue (https://github.com/QuickBlox/quickblox-flutter-sdk/issues/77). 
It will help us identify you quickly and continue secure conversation for our team to properly assist you.
