### ISSUE TITLE
Unable to get the User Id of a Logged in User

### ISSUE THREAD

**Issue by uzairamer** [QuickBlox/quickblox-flutter-sdk#8]
After initializing, when I try to log in, `QBLoginResult` has everything initialized to null. 

![issue_with_quickblox](https://user-images.githubusercontent.com/41609549/83030863-4e9c1800-a04d-11ea-99a0-4c1f6a17cba3.png)

Although, the response of the GET request is displayed in the terminal. Can anyone please look into this? Is there a way to get the GET request's response in the meanwhile?

Thanks,

**Comment by Heleo2705** [comment]
I am also having this issue. Please look into this.

**Comment by kirillTolmachev** [comment]
Hello.
Please try to use the last version of SDK 0.3.9-alpha.
